// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BookServiceCreateData, BookServiceCreateErrors, BookServiceCreateResponses, BookServiceDeleteData, BookServiceDeleteErrors, BookServiceDeleteResponses, BookServiceGetByIdData, BookServiceGetByIdErrors, BookServiceGetByIdResponses, BookServiceListData, BookServiceListErrors, BookServiceListResponses, BookServiceStatsData, BookServiceStatsErrors, BookServiceStatsResponses, BookServiceUpdateData, BookServiceUpdateErrors, BookServiceUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all books
 *
 * Returns all books in the library collection.
 */
export const bookServiceList = <ThrowOnError extends boolean = false>(options?: Options<BookServiceListData, ThrowOnError>) => (options?.client ?? client).get<BookServiceListResponses, BookServiceListErrors, ThrowOnError>({ url: '/', ...options });

/**
 * Create a book
 *
 * Creates a new book in the library collection.
 */
export const bookServiceCreate = <ThrowOnError extends boolean = false>(options: Options<BookServiceCreateData, ThrowOnError>) => (options.client ?? client).post<BookServiceCreateResponses, BookServiceCreateErrors, ThrowOnError>({
    url: '/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a book
 *
 * Deletes a book from the library collection by ID.
 */
export const bookServiceDelete = <ThrowOnError extends boolean = false>(options: Options<BookServiceDeleteData, ThrowOnError>) => (options.client ?? client).delete<BookServiceDeleteResponses, BookServiceDeleteErrors, ThrowOnError>({ url: '/{id}', ...options });

/**
 * Get a book by ID
 *
 * Returns a single book by its unique ID.
 */
export const bookServiceGetById = <ThrowOnError extends boolean = false>(options: Options<BookServiceGetByIdData, ThrowOnError>) => (options.client ?? client).get<BookServiceGetByIdResponses, BookServiceGetByIdErrors, ThrowOnError>({ url: '/{id}', ...options });

/**
 * Update a book
 *
 * Partially updates an existing book by ID.
 */
export const bookServiceUpdate = <ThrowOnError extends boolean = false>(options: Options<BookServiceUpdateData, ThrowOnError>) => (options.client ?? client).patch<BookServiceUpdateResponses, BookServiceUpdateErrors, ThrowOnError>({
    url: '/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get library statistics
 *
 * Returns aggregate statistics about the books in the library.
 */
export const bookServiceStats = <ThrowOnError extends boolean = false>(options?: Options<BookServiceStatsData, ThrowOnError>) => (options?.client ?? client).get<BookServiceStatsResponses, BookServiceStatsErrors, ThrowOnError>({ url: '/stats', ...options });
