// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://itmd544-mid-dbabfjgna0hnbgf8.canadacentral-01.azurewebsites.net' | (string & {});
};

/**
 * A book in the library.
 */
export type Book = {
    /**
     * Unique identifier for the book.
     */
    readonly id?: string;
    /**
     * The title of the book.
     */
    title: string;
    /**
     * The author of the book.
     */
    author: string;
    /**
     * The ISBN of the book.
     */
    isbn: string;
    /**
     * The genre of the book.
     */
    genre: 'fiction' | 'non-fiction' | 'fantasy' | 'sci-fi' | 'mystery';
    /**
     * The year the book was published.
     */
    publishedYear: number;
};

/**
 * Input schema for creating a book.
 */
export type BookCreate = {
    /**
     * The title of the book.
     */
    title: string;
    /**
     * The author of the book.
     */
    author: string;
    /**
     * The ISBN of the book.
     */
    isbn: string;
    /**
     * The genre of the book.
     */
    genre: 'fiction' | 'non-fiction' | 'fantasy' | 'sci-fi' | 'mystery';
    /**
     * The year the book was published.
     */
    publishedYear: number;
};

/**
 * Input schema for updating a book.
 */
export type BookUpdate = {
    /**
     * The title of the book.
     */
    title?: string;
    /**
     * The author of the book.
     */
    author?: string;
    /**
     * The ISBN of the book.
     */
    isbn?: string;
    /**
     * The genre of the book.
     */
    genre?: 'fiction' | 'non-fiction' | 'fantasy' | 'sci-fi' | 'mystery';
    /**
     * The year the book was published.
     */
    publishedYear?: number;
};

/**
 * Statistics about the library collection.
 */
export type BookStats = {
    /**
     * Total number of books in the library.
     */
    totalBooks?: number;
    /**
     * The average publication year of all books.
     */
    averagePublishedYear?: number;
    /**
     * A count of books grouped by genre.
     */
    booksByGenre?: {
        [key: string]: number;
    };
};

/**
 * Error response object.
 */
export type ErrorResponse = {
    /**
     * A human-readable error message.
     */
    message: string;
};

/**
 * A book in the library.
 */
export type BookWritable = {
    /**
     * The title of the book.
     */
    title: string;
    /**
     * The author of the book.
     */
    author: string;
    /**
     * The ISBN of the book.
     */
    isbn: string;
    /**
     * The genre of the book.
     */
    genre: 'fiction' | 'non-fiction' | 'fantasy' | 'sci-fi' | 'mystery';
    /**
     * The year the book was published.
     */
    publishedYear: number;
};

export type BookServiceListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type BookServiceListErrors = {
    /**
     * Bad request.
     */
    400: ErrorResponse;
};

export type BookServiceListError = BookServiceListErrors[keyof BookServiceListErrors];

export type BookServiceListResponses = {
    /**
     * A list of books.
     */
    200: Array<Book>;
};

export type BookServiceListResponse = BookServiceListResponses[keyof BookServiceListResponses];

export type BookServiceCreateData = {
    body: BookCreate;
    path?: never;
    query?: never;
    url: '/';
};

export type BookServiceCreateErrors = {
    /**
     * Bad request.
     */
    400: ErrorResponse;
};

export type BookServiceCreateError = BookServiceCreateErrors[keyof BookServiceCreateErrors];

export type BookServiceCreateResponses = {
    /**
     * Book created successfully.
     */
    201: Book;
};

export type BookServiceCreateResponse = BookServiceCreateResponses[keyof BookServiceCreateResponses];

export type BookServiceDeleteData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the book.
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type BookServiceDeleteErrors = {
    /**
     * Bad request.
     */
    400: ErrorResponse;
    /**
     * Book not found.
     */
    404: ErrorResponse;
};

export type BookServiceDeleteError = BookServiceDeleteErrors[keyof BookServiceDeleteErrors];

export type BookServiceDeleteResponses = {
    /**
     * Book deleted successfully.
     */
    200: Book;
};

export type BookServiceDeleteResponse = BookServiceDeleteResponses[keyof BookServiceDeleteResponses];

export type BookServiceGetByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the book.
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type BookServiceGetByIdErrors = {
    /**
     * Bad request.
     */
    400: ErrorResponse;
    /**
     * Book not found.
     */
    404: ErrorResponse;
};

export type BookServiceGetByIdError = BookServiceGetByIdErrors[keyof BookServiceGetByIdErrors];

export type BookServiceGetByIdResponses = {
    /**
     * The requested book.
     */
    200: Book;
};

export type BookServiceGetByIdResponse = BookServiceGetByIdResponses[keyof BookServiceGetByIdResponses];

export type BookServiceUpdateData = {
    body: BookUpdate;
    path: {
        /**
         * The unique identifier of the book.
         */
        id: string;
    };
    query?: never;
    url: '/{id}';
};

export type BookServiceUpdateErrors = {
    /**
     * Bad request.
     */
    400: ErrorResponse;
    /**
     * Book not found.
     */
    404: ErrorResponse;
};

export type BookServiceUpdateError = BookServiceUpdateErrors[keyof BookServiceUpdateErrors];

export type BookServiceUpdateResponses = {
    /**
     * Book updated successfully.
     */
    200: Book;
};

export type BookServiceUpdateResponse = BookServiceUpdateResponses[keyof BookServiceUpdateResponses];

export type BookServiceStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type BookServiceStatsErrors = {
    /**
     * Bad request.
     */
    400: ErrorResponse;
};

export type BookServiceStatsError = BookServiceStatsErrors[keyof BookServiceStatsErrors];

export type BookServiceStatsResponses = {
    /**
     * Library statistics returned successfully.
     */
    200: BookStats;
};

export type BookServiceStatsResponse = BookServiceStatsResponses[keyof BookServiceStatsResponses];
